[input]
html_selector = "main"
base_directory = "/Users/virantha/dev/blog_new/output"

[[input.files]]
path = "index.html"
url = "/index.html"
title = "About Me"

[[input.files]]
path = "2021/04/01/edgeos-dnsmasq-client-specific-dns-dhcp/index.html"
url = "/2021/04/01/edgeos-dnsmasq-client-specific-dns-dhcp/"
title = "Client-specific DNS and DHCP settings with Dnsmasq and Edgeos / Edgerouter"

[[input.files]]
path = "2019/05/20/choosing-a-thunderbolt-3-dock-macbook/index.html"
url = "/2019/05/20/choosing-a-thunderbolt-3-dock-macbook/"
title = "Best Docking Stations for Apple MacBooks - Thunderbolt 3 or USB-C?"

[[input.files]]
path = "2019/04/04/lego-spike-prime-compared/index.html"
url = "/2019/04/04/lego-spike-prime-compared/"
title = "LEGO®'s new SPIKE Prime BluetoothLE Controlled Robotics Kit"

[[input.files]]
path = "2019/03/30/bricknil/index.html"
url = "/2019/03/30/bricknil/"
title = "BrickNil - Control LEGO Bluetooth Sensors and Motors with Python"

[[input.files]]
path = "2019/03/30/raspberry-pi-setup-with-ansible-python-37/index.html"
url = "/2019/03/30/raspberry-pi-setup-with-ansible-python-37/"
title = "Setting up a Raspberry Pi with Python 3.7+ using Ansible"

[[input.files]]
path = "2017/09/28/hardware-simulation-using-curio-3/index.html"
url = "/2017/09/28/hardware-simulation-using-curio-3/"
title = "Part 3 - Building a Fast Event-Driven Simulator for Concurrent Systems of Hardware Processes Using Curio and Python 3.6"

[[input.files]]
path = "2017/09/27/hardware-simulation-using-curio-2/index.html"
url = "/2017/09/27/hardware-simulation-using-curio-2/"
title = "Part 2 - Building a Fast Event-Driven Simulator for Concurrent Systems of Hardware Processes Using Curio and Python 3.6"

[[input.files]]
path = "2017/09/22/hardware-simulation-using-curio/index.html"
url = "/2017/09/22/hardware-simulation-using-curio/"
title = "Part 1 - Building a Fast Event-Driven Simulator for Concurrent Systems of Hardware Processes Using Curio and Python 3.6"

[[input.files]]
path = "2016/11/28/moneydance-python-extension-tips/index.html"
url = "/2016/11/28/moneydance-python-extension-tips/"
title = "How to use Python to generate extensions with a GUI for Moneydance 2017"

[[input.files]]
path = "2016/11/07/photokeeper-usage-guide/index.html"
url = "/2016/11/07/photokeeper-usage-guide/"
title = "PhotoKeeper: Usage guide"

[[input.files]]
path = "2016/10/13/funds-gather-framework-for-scraping-financial-information/index.html"
url = "/2016/10/13/funds-gather-framework-for-scraping-financial-information/"
title = "FundsGather -- A starter framework for scraping financial information"

[[input.files]]
path = "2016/07/06/parent-guide-to-starting-pokemon/index.html"
url = "/2016/07/06/parent-guide-to-starting-pokemon/"
title = "Getting started with the Pokemon Trading Card Game (TCG) for parents"

[[input.files]]
path = "2016/06/23/elegant-command-line-parsing-in-python/index.html"
url = "/2016/06/23/elegant-command-line-parsing-in-python/"
title = "Elegant command line parsing in Python using docopt, schema, and yaml"

[[input.files]]
path = "2016/04/07/updated-reverse-engineering-nissan-connect-ev-protocol/index.html"
url = "/2016/04/07/updated-reverse-engineering-nissan-connect-ev-protocol/"
title = "[UPDATED] Reverse engineering the remote control protocol for the Nissan LEAF (the new Nissan EV protocol)"

[[input.files]]
path = "2016/03/10/example-provisioning-of-hackt-using-vagrant-ansible/index.html"
url = "/2016/03/10/example-provisioning-of-hackt-using-vagrant-ansible/"
title = "An Example Provisioning of HACKT on a Centos 7 VM using Vagrant and Ansible"

[[input.files]]
path = "2016/01/12/reverse-engineering-nissan-connect-ev-protocol/index.html"
url = "/2016/01/12/reverse-engineering-nissan-connect-ev-protocol/"
title = "Reverse engineering the remote control protocol for the Nissan LEAF (the new Nissan EV protocol)"

[[input.files]]
path = "2015/04/07/oneresume-a-data-driven-resume-generator-for-microsoft-word/index.html"
url = "/2015/04/07/oneresume-a-data-driven-resume-generator-for-microsoft-word/"
title = "OneResumé - Usage Guide"

[[input.files]]
path = "2015/03/09/migrating-xenserver-vdi-to-kvm/index.html"
url = "/2015/03/09/migrating-xenserver-vdi-to-kvm/"
title = "Migrating XenServer Virtual Machine VDIs to KVM"

[[input.files]]
path = "2015/01/26/building-a-low-power-file-server-intel-avoton/index.html"
url = "/2015/01/26/building-a-low-power-file-server-intel-avoton/"
title = "Building a low-power home file server using Intel's Avoton platform"

[[input.files]]
path = "2014/08/22/setting-up-edgemax-edgerouter-lite-erlite-3/index.html"
url = "/2014/08/22/setting-up-edgemax-edgerouter-lite-erlite-3/"
title = "Setting up the Edgemax EdgeRouter Lite (ERLite-3) in a Home Environment"

[[input.files]]
path = "2014/05/21/ubuntu-14-04-trusty-on-xenserver-62/index.html"
url = "/2014/05/21/ubuntu-14-04-trusty-on-xenserver-62/"
title = "Installing Ubuntu 14.04 LTS (Trusty Tahir) VM on a XenServer 6.2 host"

[[input.files]]
path = "2014/05/12/existing-tab-stop-manipulation-in-vim/index.html"
url = "/2014/05/12/existing-tab-stop-manipulation-in-vim/"
title = "Changing tab stops in Vim"

[[input.files]]
path = "2014/05/08/setting-up-new-project-using-google-oauth2-api/index.html"
url = "/2014/05/08/setting-up-new-project-using-google-oauth2-api/"
title = "Setting up Google Oauth2 API"

[[input.files]]
path = "2014/05/07/ember-js-oauth2-implicit-grant-example/index.html"
url = "/2014/05/07/ember-js-oauth2-implicit-grant-example/"
title = "Example of how to authenticate using Oauth2 in Ember.js using Implicit Grant (client-side)"

[[input.files]]
path = "2014/04/15/replacing-noisy-fan-broan-bathroom-688/index.html"
url = "/2014/04/15/replacing-noisy-fan-broan-bathroom-688/"
title = "Replacing a Noisy Broan Bathroom Fan (Builder's grade 688)"

[[input.files]]
path = "2014/03/30/images-color-and-blank-detection/index.html"
url = "/2014/03/30/images-color-and-blank-detection/"
title = "Detecting color vs greyscale and blank pages during scanning"

[[input.files]]
path = "2014/03/30/scanpdf-usage-guide/index.html"
url = "/2014/03/30/scanpdf-usage-guide/"
title = "ScanPDF - Usage guide"

[[input.files]]
path = "2014/03/24/clang-mavericks-error-workaround/index.html"
url = "/2014/03/24/clang-mavericks-error-workaround/"
title = "Getting around Xcode 5.1 clang -mno-fused-madd error"

[[input.files]]
path = "2014/03/17/one-touch-scanning-with-fujitsu-scansnap-in-linux/index.html"
url = "/2014/03/17/one-touch-scanning-with-fujitsu-scansnap-in-linux/"
title = "One-touch scan enabling in Ubuntu Linux for the Fujitsu ScanSnap S1500"

[[input.files]]
path = "2014/03/11/font-rendering-fix-chrome/index.html"
url = "/2014/03/11/font-rendering-fix-chrome/"
title = "Font rendering fix in Chrome"

[[input.files]]
path = "2014/03/08/pound-reverse-proxy-easy-to-use-hostnames/index.html"
url = "/2014/03/08/pound-reverse-proxy-easy-to-use-hostnames/"
title = "Pound reverse proxy and simpler URLs for webapps (Sickbeard, Plex, CouchPotato, Headphones, SABNZBD)"

[[input.files]]
path = "2014/03/02/fix-your-breville-smart-oven-by-replacing-the-thermal-fuse/index.html"
url = "/2014/03/02/fix-your-breville-smart-oven-by-replacing-the-thermal-fuse/"
title = "Fix your Breville Smart Oven by replacing the thermal fuse"

[[input.files]]
path = "2014/02/02/digital-toaster-oven-survey/index.html"
url = "/2014/02/02/digital-toaster-oven-survey/"
title = "Digital Toaster Oven Options"

[[input.files]]
path = "2014/01/10/airframe-usage-guide/index.html"
url = "/2014/01/10/airframe-usage-guide/"
title = "AirFrame: Usage guide"

[[input.files]]
path = "2014/01/09/hacking-together-a-wifi-photo-frame-with-a-toshiba-flashair-sd-card-wireless-photo-uploads/index.html"
url = "/2014/01/09/hacking-together-a-wifi-photo-frame-with-a-toshiba-flashair-sd-card-wireless-photo-uploads/"
title = "AirFrame: Hacking together a WiFi photo frame with a Toshiba FlashAir SD card and Flickr"

[[input.files]]
path = "2013/11/14/starting-a-simple-flask-app-with-heroku/index.html"
url = "/2013/11/14/starting-a-simple-flask-app-with-heroku/"
title = "Starting a simple Flask app with Heroku"

[[input.files]]
path = "2013/11/04/creating-new-notes-and-attaching-files-using-evernotes-python-api/index.html"
url = "/2013/11/04/creating-new-notes-and-attaching-files-using-evernotes-python-api/"
title = "Creating new notes and attaching files using Evernote's Python API"

[[input.files]]
path = "2013/09/29/quick-web-app-with-go-ember-js-and-mongodb/index.html"
url = "/2013/09/29/quick-web-app-with-go-ember-js-and-mongodb/"
title = "Quick web app with Go, Ember.js, and MongoDB"

[[input.files]]
path = "2013/09/04/pyyaml-include-yaml-files-within-yaml-files/index.html"
url = "/2013/09/04/pyyaml-include-yaml-files-within-yaml-files/"
title = "PyYAML: Include yaml files within yaml files"

[[input.files]]
path = "2013/08/16/reading-and-writing-microsoft-word-docx-files-with-python/index.html"
url = "/2013/08/16/reading-and-writing-microsoft-word-docx-files-with-python/"
title = "Reading and writing Microsoft Word docx files with Python"

[[input.files]]
path = "2013/07/23/pypdfocr-a-python-script-for-running-free-ocr-on-your-pdfs/index.html"
url = "/2013/07/23/pypdfocr-a-python-script-for-running-free-ocr-on-your-pdfs/"
title = "PyPDFOCR - Guide to Usage"

[[input.files]]
path = "2013/07/22/pyocr-a-python-script-for-running-free-ocr-on-your-pdfs/index.html"
url = "/2013/07/22/pyocr-a-python-script-for-running-free-ocr-on-your-pdfs/"
title = "PyPDFOCR - A Python Script for Free OCR on Your PDFs using Tesseract"

[[input.files]]
path = "2013/07/03/bluetooth-headset-with-dedicated-mute-button/index.html"
url = "/2013/07/03/bluetooth-headset-with-dedicated-mute-button/"
title = "Bluetooth headset with dedicated mute button"

[[input.files]]
path = "2013/04/20/python-auto-sort-of-ocred-pdfs/index.html"
url = "/2013/04/20/python-auto-sort-of-ocred-pdfs/"
title = "Python auto sort of OCR'ed PDFs"

[[input.files]]
path = "2013/03/01/better-vim-for-python/index.html"
url = "/2013/03/01/better-vim-for-python/"
title = "Better VIM for Python"

[[input.files]]
path = "2013/01/13/replacing-the-upstream-oxygen-o2-sensor-in-a-honda-civic-2005/index.html"
url = "/2013/01/13/replacing-the-upstream-oxygen-o2-sensor-in-a-honda-civic-2005/"
title = "Replacing the upstream oxygen (O2) sensor in a Honda Civic 2005"

[[input.files]]
path = "2012/11/02/class-based-decorators-in-python/index.html"
url = "/2012/11/02/class-based-decorators-in-python/"
title = "Class-based decorators in Python"

[[input.files]]
path = "2012/10/25/getting-rid-of-paper-clutter/index.html"
url = "/2012/10/25/getting-rid-of-paper-clutter/"
title = "Getting rid of paper clutter"

[[input.files]]
path = "2012/10/23/using-calibre-to-manage-my-e-books/index.html"
url = "/2012/10/23/using-calibre-to-manage-my-e-books/"
title = "Using Calibre to manage my e-books"

[output]
excerpts_per_result = 1
